### ISSUE TITLE
React Styled Component Grid

### ISSUE THREAD

**Issue by bradyclifford** [im-enrollment/bootstrap-npm-starter#6]
What are the thoughts around "not" adding css attributes to our React Components when we want to integrate grids, but rather use a styled component?

Have we thought about using a library like:
https://www.npmjs.com/package/styled-bootstrap-grid

We can still customize the css you are adding to `es-assets` to a company standard of how our grids react keeping it framework agnostic.

But another idea is to not expose a css stylesheet and rather use a styled-componment Theme Provider, no need to manage a css source through a CDN.

**Comment by zlaja1983** [comment]
We wanted to go with purely CSS solution and have it be framework agnostic. @Darrken can expand on this more.  Perhaps we can have this stay as a github issue for now and have a broader conversation. But grid.css and util.css are already part of our es-assets and would not like to hold teams back from not using them at this point.

**Comment by bradyclifford** [comment]
Ya I am not saying you use styled-component grids across all the teams.  Each team should be able to decide "how" they want to use the `grid.css` and `util.css` in their applications.  If a team wants to just add a `class="` attribute to their React Components, great.  If a team wants to use a styled component instead to represent the columns and rows, great.  Both solutions are still using the standardized grid css provided in the `es-assets`.

**Comment by Darrken** [comment]
What benefits would using `styled-bootstrap-grid` have over the vanilla CSS and being able to point to [simple docs](https://getbootstrap.com/docs/4.0/layout/grid/)? At first glance, it seems like it's just adding a complex wrapper to something that's already pretty simple to use. It supports a grid theme and some customizations, but I thought the point of settling on a grid standard was so nobody had to think about those things.

**Comment by bradyclifford** [comment]
Thanks for your input @Darrken .  You and @zlaja1983 make good points.

Overall, how the css is consumed and used by the teams should be up to the teams.  I don't think either of you are mandating how the standard is implemented.
